namespace Bukit.Cli.Commands;

public static class VisualCommand
{
    public static async Task<int> RunAsync(ArgReader reader)
    {
        var subcommand = reader.GetArg(1);
        if (string.Equals(subcommand, "generate", StringComparison.OrdinalIgnoreCase))
        {
            var config = reader.GetOption("--config") ?? "site.yaml";
            var baseUrl = reader.GetOption("--site-url") ?? "http://localhost:4173";
            var outputDir = reader.GetOption("--dir") ?? "dist";
            var outFile = reader.GetOption("--out") ?? "visual-tests.spec.js";
            return await GenerateAsync(config, outputDir, baseUrl, outFile);
        }

        PrintHelp();
        return 2;
    }

    private static void PrintHelp()
    {
        Console.WriteLine("Usage: bukit visual generate [--config site.yaml] [--dir dist] [--site-url http://localhost:4173] [--out visual-tests.spec.js]");
        Console.WriteLine();
        Console.WriteLine("  generate    Generate a Playwright test script for visual validation.");
        Console.WriteLine("              After building, run: npx playwright test visual-tests.spec.js");
    }

    private static Task<int> GenerateAsync(string configPath, string outputDir, string baseUrl, string outFile)
    {
        if (!File.Exists(configPath))
        {
            Console.Error.WriteLine($"Config not found: {configPath}");
            return Task.FromResult(2);
        }

        if (!Directory.Exists(outputDir))
        {
            Console.Error.WriteLine($"Output directory not found: {outputDir}. Run 'bukit build' first.");
            return Task.FromResult(2);
        }

        var pages = DiscoverPages(outputDir);
        if (pages.Count == 0)
        {
            pages.Add("/");
        }

        var script = GeneratePlaywrightScript(baseUrl, pages);
        File.WriteAllText(outFile, script);

        Console.WriteLine($"Generated {outFile} with {pages.Count} page(s) to test.");
        Console.WriteLine();
        Console.WriteLine("To run visual tests:");
        Console.WriteLine($"  1. Start preview server: bukit preview --dir {outputDir}");
        Console.WriteLine("  2. Install Playwright:   npm init -y && npm install @playwright/test");
        Console.WriteLine($"  3. Run tests:            npx playwright test {outFile} --reporter=list");
        return Task.FromResult(0);
    }

    private static List<string> DiscoverPages(string outputDir)
    {
        var pages = new List<string>();
        var files = Directory.GetFiles(outputDir, "*.html", SearchOption.AllDirectories);
        foreach (var file in files)
        {
            var relPath = Path.GetRelativePath(outputDir, file);
            var url = "/" + relPath.Replace('\\', '/');
            if (url.EndsWith("/index.html", StringComparison.OrdinalIgnoreCase))
            {
                url = url[..^"/index.html".Length];
                if (!url.EndsWith('/'))
                {
                    url += "/";
                }
            }
            pages.Add(url);
        }

        pages.Sort(StringComparer.Ordinal);
        return pages;
    }

    private static string GeneratePlaywrightScript(string baseUrl, List<string> pages)
    {
        var testCases = new System.Text.StringBuilder();
        foreach (var pageUrl in pages)
        {
            var safeName = pageUrl.Replace("/", "-").Replace(":", "").Trim('-');
            if (string.IsNullOrEmpty(safeName))
            {
                safeName = "home";
            }

            testCases.AppendLine($"  test('{pageUrl}', async ({{ page }}) => {{");
            testCases.AppendLine($"    const response = await page.goto('{baseUrl}{pageUrl}');");
            testCases.AppendLine($"    expect(response?.status()).toBe(200);");
            testCases.AppendLine($"    await expect(page).toHaveScreenshot('{safeName}.png', {{ fullPage: true }});");
            testCases.AppendLine($"  }});");
            testCases.AppendLine();
        }

        return "// Generated by bukit visual generate\n"
            + "const { test, expect } = require('@playwright/test');\n\n"
            + "test.describe('Bukit Visual Tests', () => {\n"
            + testCases
            + "});\n";
    }
}
