<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Bukit.Plugin.WechatSync.Tests" />
    <InternalsVisibleTo Include="bukit-plugin-wechat-sync" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Bukit-Core\Bukit.Notion\Bukit.Notion.csproj" />
    <ProjectReference Include="..\..\Bukit-Core\Bukit.Shared\Bukit.Shared.csproj" />
  </ItemGroup>

</Project>
