site:
  name: my-demo
  title: my-demo
  baseUrl: /
  language: zh-CN
  seo:
    renderMode: 'off'
  collections:
    page:
      permalink: '/{slug}/'
      template: 'pages/page.html'
      listRoute: '/'
content:
  provider: markdown
  contentDir: content
theme:
  name: my-demo
