<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>bukit-labs</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bukit.Cli.Shared\Bukit.Cli.Shared.csproj" />
    <ProjectReference Include="..\..\src\Bukit.Config\Bukit.Config.csproj" />
    <ProjectReference Include="..\..\src\Bukit.Engine\Bukit.Engine.csproj" />
    <ProjectReference Include="..\..\src\Bukit.Engine.Abstractions\Bukit.Engine.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Bukit.Importing\Bukit.Importing.csproj" />
    <ProjectReference Include="..\..\src\Bukit.Shared\Bukit.Shared.csproj" />
    <ProjectReference Include="..\..\src\Bukit.Theme\Bukit.Theme.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Bukit.Labs.Cli.Tests" />
  </ItemGroup>

</Project>
