#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

CORE_COVERAGE_THRESHOLD="${CORE_COVERAGE_THRESHOLD:-${COVERAGE_THRESHOLD:-80}}"
CLI_COVERAGE_THRESHOLD="${CLI_COVERAGE_THRESHOLD:-${COVERAGE_THRESHOLD:-75}}"

CI_FULL_SKIP_FAST=0 \
CORE_COVERAGE_THRESHOLD="$CORE_COVERAGE_THRESHOLD" \
CLI_COVERAGE_THRESHOLD="$CLI_COVERAGE_THRESHOLD" \
bash scripts/gates/ci-fast.sh "${1:-Release}"
