#!/usr/bin/env node
// Bukit External Plugin Example — Derive Pages
// Usage: node hello-derive.js
// Reads JSON request from stdin, writes JSON response to stdout.

const { exit, stdin, stdout } = require("process");

let raw = "";
stdin.setEncoding("utf-8");
stdin.on("data", (chunk) => { raw += chunk; });
stdin.on("end", () => {
    let request;
    try {
        request = JSON.parse(raw);
    } catch {
        stdout.write(JSON.stringify({ ok: false, error: "Invalid JSON input" }));
        exit(1);
    }

    const hook = request.hook;
    if (hook === "handshake") {
        stdout.write(JSON.stringify({ ok: true, supportedHooks: ["derive-pages"], negotiatedSchemaVersion: "2" }));
        exit(0);
    }

    if (hook === "derive-pages") {
        const routedCount = (request.derivePages && request.derivePages.routedPages)
            ? request.derivePages.routedPages.length
            : 0;

        stdout.write(JSON.stringify({
            ok: true,
            derivedPages: [{
                id: "hello-from-plugin",
                title: `Hello from External Plugin! (${routedCount} pages)`,
                slug: "hello",
                url: "/hello/",
                outputPath: "hello/index.html",
                template: null,
                contentHtml: `<p>This page was generated by a Node.js external plugin.</p>
<p>Total routed pages in this build: <strong>${routedCount}</strong></p>`,
                meta: {},
                fields: {},
                publishAt: new Date().toISOString()
            }],
            logs: [{ level: "info", message: `Derived 1 page from ${routedCount} routed pages` }]
        }));
        exit(0);
    }

    stdout.write(JSON.stringify({ ok: false, error: `Unknown hook: ${hook}` }));
    exit(1);
});
